"""
Generate markdown reports from Claude evaluations
"""
import os
from datetime import datetime
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ReportGenerator:
    def __init__(self, output_dir: str):
        """
        Initialize report generator

        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_report(
        self,
        video_name: str,
        video_path: str,
        evaluation: str,
        transcript_summary: dict,
        num_frames: int,
        processing_time: float
    ) -> str:
        """
        Generate markdown report for video evaluation

        Args:
            video_name: Name of video
            video_path: Path to original video
            evaluation: Claude's evaluation text
            transcript_summary: Dictionary with transcript stats
            num_frames: Number of frames analyzed
            processing_time: Time taken to process (seconds)

        Returns:
            Path to generated report file
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Create report content
        report_lines = []
        report_lines.append(f"# Video Evaluation Report: {video_name}")
        report_lines.append(f"\n**Generated:** {timestamp}\n")

        # Video metadata section
        report_lines.append("## Video Information\n")
        report_lines.append(f"- **File:** `{Path(video_path).name}`")
        report_lines.append(f"- **Full Path:** `{video_path}`")
        report_lines.append(f"- **Duration:** {transcript_summary.get('duration_seconds', 0):.1f} seconds")
        report_lines.append(f"- **Frames Analyzed:** {num_frames}")
        report_lines.append(f"- **Processing Time:** {processing_time:.1f} seconds")
        report_lines.append("")

        # Transcript metadata
        report_lines.append("## Transcript Summary\n")
        report_lines.append(f"- **Language:** {transcript_summary.get('language', 'unknown')}")
        report_lines.append(f"- **Total Words:** {transcript_summary.get('total_words', 0)}")
        report_lines.append(f"- **Segments:** {transcript_summary.get('num_segments', 0)}")
        report_lines.append(f"- **Words per Minute:** {transcript_summary.get('words_per_minute', 0):.1f}")
        report_lines.append("")

        # Divider before evaluation
        report_lines.append("---\n")

        # Claude's evaluation
        report_lines.append("## Educational Evaluation\n")
        report_lines.append(evaluation)
        report_lines.append("")

        # Footer
        report_lines.append("\n---")
        report_lines.append(f"\n*Report generated by Kids Video Evaluator on {timestamp}*")

        # Write report to file
        safe_name = self._sanitize_filename(video_name)
        report_filename = f"{safe_name}_evaluation.md"
        report_path = os.path.join(self.output_dir, report_filename)

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report_lines))

        logger.info(f"✓ Report saved: {report_path}")
        return report_path

    def _sanitize_filename(self, filename: str) -> str:
        """Remove or replace characters that are invalid in filenames"""
        # Remove extension if present
        name = Path(filename).stem

        # Replace invalid characters
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            name = name.replace(char, '_')

        # Remove leading/trailing spaces and dots
        name = name.strip('. ')

        # Limit length
        if len(name) > 200:
            name = name[:200]

        return name

    def generate_summary_report(
        self,
        video_reports: list,
        total_processing_time: float
    ) -> str:
        """
        Generate a summary report for multiple videos

        Args:
            video_reports: List of tuples (video_name, report_path)
            total_processing_time: Total time for all videos

        Returns:
            Path to summary report
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        report_lines = []
        report_lines.append("# Batch Video Evaluation Summary\n")
        report_lines.append(f"**Generated:** {timestamp}")
        report_lines.append(f"**Total Videos Processed:** {len(video_reports)}")
        report_lines.append(f"**Total Processing Time:** {total_processing_time / 60:.1f} minutes\n")

        report_lines.append("## Evaluated Videos\n")
        for i, (video_name, report_path) in enumerate(video_reports, 1):
            rel_path = Path(report_path).name
            report_lines.append(f"{i}. **{video_name}**")
            report_lines.append(f"   - Report: [{rel_path}](./{rel_path})")

        report_lines.append(f"\n---\n*Generated by Kids Video Evaluator*")

        # Write summary
        summary_path = os.path.join(
            self.output_dir,
            f"_SUMMARY_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        )

        with open(summary_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report_lines))

        logger.info(f"✓ Summary report saved: {summary_path}")
        return summary_path
